// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FbsContentHeadM : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsContentHeadM GetRootAsFbsContentHeadM(ByteBuffer _bb) { return GetRootAsFbsContentHeadM(_bb, new FbsContentHeadM()); }
  public static FbsContentHeadM GetRootAsFbsContentHeadM(ByteBuffer _bb, FbsContentHeadM obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsContentHeadM __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort PacketType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public int ConDataLen { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }

  public static Offset<FbsClassM.FbsContentHeadM> CreateFbsContentHeadM(FlatBufferBuilder builder,
      ushort packetType = 0,
      int conDataLen = -1) {
    builder.StartTable(2);
    FbsContentHeadM.AddConDataLen(builder, conDataLen);
    FbsContentHeadM.AddPacketType(builder, packetType);
    return FbsContentHeadM.EndFbsContentHeadM(builder);
  }

  public static void StartFbsContentHeadM(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPacketType(FlatBufferBuilder builder, ushort packetType) { builder.AddUshort(0, packetType, 0); }
  public static void AddConDataLen(FlatBufferBuilder builder, int conDataLen) { builder.AddInt(1, conDataLen, -1); }
  public static Offset<FbsClassM.FbsContentHeadM> EndFbsContentHeadM(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsContentHeadM>(o);
  }
}


static public class FbsContentHeadMVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PacketType*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 6 /*ConDataLen*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
