// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

///////////////////////////////////////////////////////////////
public struct FbsEncryptKey : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsEncryptKey GetRootAsFbsEncryptKey(ByteBuffer _bb) { return GetRootAsFbsEncryptKey(_bb, new FbsEncryptKey()); }
  public static FbsEncryptKey GetRootAsFbsEncryptKey(ByteBuffer _bb, FbsEncryptKey obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsEncryptKey __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte Key(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int KeyLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetKeyBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetKeyBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetKeyArray() { return __p.__vector_as_array<byte>(4); }
  public byte Iv(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int IvLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIvBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetIvBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetIvArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<FbsClassM.FbsEncryptKey> CreateFbsEncryptKey(FlatBufferBuilder builder,
      VectorOffset keyOffset = default(VectorOffset),
      VectorOffset ivOffset = default(VectorOffset)) {
    builder.StartTable(2);
    FbsEncryptKey.AddIv(builder, ivOffset);
    FbsEncryptKey.AddKey(builder, keyOffset);
    return FbsEncryptKey.EndFbsEncryptKey(builder);
  }

  public static void StartFbsEncryptKey(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddKey(FlatBufferBuilder builder, VectorOffset keyOffset) { builder.AddOffset(0, keyOffset.Value, 0); }
  public static VectorOffset CreateKeyVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateKeyVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateKeyVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateKeyVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartKeyVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddIv(FlatBufferBuilder builder, VectorOffset ivOffset) { builder.AddOffset(1, ivOffset.Value, 0); }
  public static VectorOffset CreateIvVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateIvVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateIvVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateIvVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartIvVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<FbsClassM.FbsEncryptKey> EndFbsEncryptKey(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsEncryptKey>(o);
  }
}


static public class FbsEncryptKeyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Key*/, 1 /*byte*/, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*Iv*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
