// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FbsEncryptHeadM : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsEncryptHeadM GetRootAsFbsEncryptHeadM(ByteBuffer _bb) { return GetRootAsFbsEncryptHeadM(_bb, new FbsEncryptHeadM()); }
  public static FbsEncryptHeadM GetRootAsFbsEncryptHeadM(ByteBuffer _bb, FbsEncryptHeadM obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsEncryptHeadM __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte IsCompress { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)-1; } }
  public int EncDataLen { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }
  public int OriginDataLen { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)-1; } }

  public static Offset<FbsClassM.FbsEncryptHeadM> CreateFbsEncryptHeadM(FlatBufferBuilder builder,
      sbyte isCompress = -1,
      int encDataLen = -1,
      int originDataLen = -1) {
    builder.StartTable(3);
    FbsEncryptHeadM.AddOriginDataLen(builder, originDataLen);
    FbsEncryptHeadM.AddEncDataLen(builder, encDataLen);
    FbsEncryptHeadM.AddIsCompress(builder, isCompress);
    return FbsEncryptHeadM.EndFbsEncryptHeadM(builder);
  }

  public static void StartFbsEncryptHeadM(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddIsCompress(FlatBufferBuilder builder, sbyte isCompress) { builder.AddSbyte(0, isCompress, -1); }
  public static void AddEncDataLen(FlatBufferBuilder builder, int encDataLen) { builder.AddInt(1, encDataLen, -1); }
  public static void AddOriginDataLen(FlatBufferBuilder builder, int originDataLen) { builder.AddInt(2, originDataLen, -1); }
  public static Offset<FbsClassM.FbsEncryptHeadM> EndFbsEncryptHeadM(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsEncryptHeadM>(o);
  }
}


static public class FbsEncryptHeadMVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*IsCompress*/, 1 /*sbyte*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*EncDataLen*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*OriginDataLen*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
