// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FbsLoginOk : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsLoginOk GetRootAsFbsLoginOk(ByteBuffer _bb) { return GetRootAsFbsLoginOk(_bb, new FbsLoginOk()); }
  public static FbsLoginOk GetRootAsFbsLoginOk(ByteBuffer _bb, FbsLoginOk obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsLoginOk __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public long Oid { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long ServerFrequency { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FbsClassM.FbsLoginOk> CreateFbsLoginOk(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      long oid = 0,
      long serverFrequency = 0) {
    builder.StartTable(3);
    FbsLoginOk.AddServerFrequency(builder, serverFrequency);
    FbsLoginOk.AddOid(builder, oid);
    FbsLoginOk.AddId(builder, idOffset);
    return FbsLoginOk.EndFbsLoginOk(builder);
  }

  public static void StartFbsLoginOk(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddOid(FlatBufferBuilder builder, long oid) { builder.AddLong(1, oid, 0); }
  public static void AddServerFrequency(FlatBufferBuilder builder, long serverFrequency) { builder.AddLong(2, serverFrequency, 0); }
  public static Offset<FbsClassM.FbsLoginOk> EndFbsLoginOk(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsLoginOk>(o);
  }
}


static public class FbsLoginOkVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Id*/, false)
      && verifier.VerifyField(tablePos, 6 /*Oid*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*ServerFrequency*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
