// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FbsLoginFin : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsLoginFin GetRootAsFbsLoginFin(ByteBuffer _bb) { return GetRootAsFbsLoginFin(_bb, new FbsLoginFin()); }
  public static FbsLoginFin GetRootAsFbsLoginFin(ByteBuffer _bb, FbsLoginFin obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsLoginFin __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Pid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<FbsClassM.FbsLoginFin> CreateFbsLoginFin(FlatBufferBuilder builder,
      uint pid = 0) {
    builder.StartTable(1);
    FbsLoginFin.AddPid(builder, pid);
    return FbsLoginFin.EndFbsLoginFin(builder);
  }

  public static void StartFbsLoginFin(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPid(FlatBufferBuilder builder, uint pid) { builder.AddUint(0, pid, 0); }
  public static Offset<FbsClassM.FbsLoginFin> EndFbsLoginFin(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsLoginFin>(o);
  }
}


static public class FbsLoginFinVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Pid*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
