// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FbsLogInIdPw : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsLogInIdPw GetRootAsFbsLogInIdPw(ByteBuffer _bb) { return GetRootAsFbsLogInIdPw(_bb, new FbsLogInIdPw()); }
  public static FbsLogInIdPw GetRootAsFbsLogInIdPw(ByteBuffer _bb, FbsLogInIdPw obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsLogInIdPw __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public string Pw { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPwBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPwBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPwArray() { return __p.__vector_as_array<byte>(6); }
  public int Version { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<FbsClassM.FbsLogInIdPw> CreateFbsLogInIdPw(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      StringOffset pwOffset = default(StringOffset),
      int version = 0) {
    builder.StartTable(3);
    FbsLogInIdPw.AddVersion(builder, version);
    FbsLogInIdPw.AddPw(builder, pwOffset);
    FbsLogInIdPw.AddId(builder, idOffset);
    return FbsLogInIdPw.EndFbsLogInIdPw(builder);
  }

  public static void StartFbsLogInIdPw(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddPw(FlatBufferBuilder builder, StringOffset pwOffset) { builder.AddOffset(1, pwOffset.Value, 0); }
  public static void AddVersion(FlatBufferBuilder builder, int version) { builder.AddInt(2, version, 0); }
  public static Offset<FbsClassM.FbsLogInIdPw> EndFbsLogInIdPw(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsLogInIdPw>(o);
  }
}


static public class FbsLogInIdPwVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Id*/, false)
      && verifier.VerifyString(tablePos, 6 /*Pw*/, false)
      && verifier.VerifyField(tablePos, 8 /*Version*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
