// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FbsMetaData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsMetaData GetRootAsFbsMetaData(ByteBuffer _bb) { return GetRootAsFbsMetaData(_bb, new FbsMetaData()); }
  public static FbsMetaData GetRootAsFbsMetaData(ByteBuffer _bb, FbsMetaData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsMetaData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string StrKey { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStrKeyBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetStrKeyBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetStrKeyArray() { return __p.__vector_as_array<byte>(4); }
  public string Header(int j) { int o = __p.__offset(6); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int HeaderLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public FbsClassM.FbsStrArray? Line(int j) { int o = __p.__offset(8); return o != 0 ? (FbsClassM.FbsStrArray?)(new FbsClassM.FbsStrArray()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int LineLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FbsClassM.FbsMetaData> CreateFbsMetaData(FlatBufferBuilder builder,
      StringOffset strKeyOffset = default(StringOffset),
      VectorOffset headerOffset = default(VectorOffset),
      VectorOffset lineOffset = default(VectorOffset)) {
    builder.StartTable(3);
    FbsMetaData.AddLine(builder, lineOffset);
    FbsMetaData.AddHeader(builder, headerOffset);
    FbsMetaData.AddStrKey(builder, strKeyOffset);
    return FbsMetaData.EndFbsMetaData(builder);
  }

  public static void StartFbsMetaData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddStrKey(FlatBufferBuilder builder, StringOffset strKeyOffset) { builder.AddOffset(0, strKeyOffset.Value, 0); }
  public static void AddHeader(FlatBufferBuilder builder, VectorOffset headerOffset) { builder.AddOffset(1, headerOffset.Value, 0); }
  public static VectorOffset CreateHeaderVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateHeaderVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateHeaderVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateHeaderVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartHeaderVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddLine(FlatBufferBuilder builder, VectorOffset lineOffset) { builder.AddOffset(2, lineOffset.Value, 0); }
  public static VectorOffset CreateLineVector(FlatBufferBuilder builder, Offset<FbsClassM.FbsStrArray>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateLineVectorBlock(FlatBufferBuilder builder, Offset<FbsClassM.FbsStrArray>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLineVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<FbsClassM.FbsStrArray>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLineVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<FbsClassM.FbsStrArray>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartLineVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FbsClassM.FbsMetaData> EndFbsMetaData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsMetaData>(o);
  }
}


static public class FbsMetaDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*StrKey*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 6 /*Header*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Line*/, FbsClassM.FbsStrArrayVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
