// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

///////////////////////////////////////////////////////////////
public struct FbsProgressBar : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsProgressBar GetRootAsFbsProgressBar(ByteBuffer _bb) { return GetRootAsFbsProgressBar(_bb, new FbsProgressBar()); }
  public static FbsProgressBar GetRootAsFbsProgressBar(ByteBuffer _bb, FbsProgressBar obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsProgressBar __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte BarType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public bool Visible { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }
  public string Title { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTitleBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTitleArray() { return __p.__vector_as_array<byte>(8); }
  public string BarText { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBarTextBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetBarTextBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetBarTextArray() { return __p.__vector_as_array<byte>(10); }
  public ushort Gage { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)65535; } }
  public ushort MaxGage { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)65535; } }
  public ushort X { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)65535; } }
  public ushort Y { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)65535; } }

  public static Offset<FbsClassM.FbsProgressBar> CreateFbsProgressBar(FlatBufferBuilder builder,
      byte barType = 0,
      bool visible = true,
      StringOffset titleOffset = default(StringOffset),
      StringOffset barTextOffset = default(StringOffset),
      ushort gage = 65535,
      ushort maxGage = 65535,
      ushort x = 65535,
      ushort y = 65535) {
    builder.StartTable(8);
    FbsProgressBar.AddBarText(builder, barTextOffset);
    FbsProgressBar.AddTitle(builder, titleOffset);
    FbsProgressBar.AddY(builder, y);
    FbsProgressBar.AddX(builder, x);
    FbsProgressBar.AddMaxGage(builder, maxGage);
    FbsProgressBar.AddGage(builder, gage);
    FbsProgressBar.AddVisible(builder, visible);
    FbsProgressBar.AddBarType(builder, barType);
    return FbsProgressBar.EndFbsProgressBar(builder);
  }

  public static void StartFbsProgressBar(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddBarType(FlatBufferBuilder builder, byte barType) { builder.AddByte(0, barType, 0); }
  public static void AddVisible(FlatBufferBuilder builder, bool visible) { builder.AddBool(1, visible, true); }
  public static void AddTitle(FlatBufferBuilder builder, StringOffset titleOffset) { builder.AddOffset(2, titleOffset.Value, 0); }
  public static void AddBarText(FlatBufferBuilder builder, StringOffset barTextOffset) { builder.AddOffset(3, barTextOffset.Value, 0); }
  public static void AddGage(FlatBufferBuilder builder, ushort gage) { builder.AddUshort(4, gage, 65535); }
  public static void AddMaxGage(FlatBufferBuilder builder, ushort maxGage) { builder.AddUshort(5, maxGage, 65535); }
  public static void AddX(FlatBufferBuilder builder, ushort x) { builder.AddUshort(6, x, 65535); }
  public static void AddY(FlatBufferBuilder builder, ushort y) { builder.AddUshort(7, y, 65535); }
  public static Offset<FbsClassM.FbsProgressBar> EndFbsProgressBar(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsProgressBar>(o);
  }
}


static public class FbsProgressBarVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*BarType*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*Visible*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 8 /*Title*/, false)
      && verifier.VerifyString(tablePos, 10 /*BarText*/, false)
      && verifier.VerifyField(tablePos, 12 /*Gage*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 14 /*MaxGage*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 16 /*X*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 18 /*Y*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
