// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
public struct FbsPkHeadM : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsPkHeadM GetRootAsFbsPkHeadM(ByteBuffer _bb) { return GetRootAsFbsPkHeadM(_bb, new FbsPkHeadM()); }
  public static FbsPkHeadM GetRootAsFbsPkHeadM(ByteBuffer _bb, FbsPkHeadM obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsPkHeadM __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Pid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ushort ConHeadLen { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public sbyte ByteCheckSum { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)-1; } }

  public static Offset<FbsClassM.FbsPkHeadM> CreateFbsPkHeadM(FlatBufferBuilder builder,
      uint pid = 0,
      ushort conHeadLen = 0,
      sbyte byteCheckSum = -1) {
    builder.StartTable(3);
    FbsPkHeadM.AddPid(builder, pid);
    FbsPkHeadM.AddConHeadLen(builder, conHeadLen);
    FbsPkHeadM.AddByteCheckSum(builder, byteCheckSum);
    return FbsPkHeadM.EndFbsPkHeadM(builder);
  }

  public static void StartFbsPkHeadM(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPid(FlatBufferBuilder builder, uint pid) { builder.AddUint(0, pid, 0); }
  public static void AddConHeadLen(FlatBufferBuilder builder, ushort conHeadLen) { builder.AddUshort(1, conHeadLen, 0); }
  public static void AddByteCheckSum(FlatBufferBuilder builder, sbyte byteCheckSum) { builder.AddSbyte(2, byteCheckSum, -1); }
  public static Offset<FbsClassM.FbsPkHeadM> EndFbsPkHeadM(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsPkHeadM>(o);
  }
}


static public class FbsPkHeadMVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Pid*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*ConHeadLen*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 8 /*ByteCheckSum*/, 1 /*sbyte*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
