// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

/////////////////////////////////////////////////////////////
public struct FbsServerTick : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsServerTick GetRootAsFbsServerTick(ByteBuffer _bb) { return GetRootAsFbsServerTick(_bb, new FbsServerTick()); }
  public static FbsServerTick GetRootAsFbsServerTick(ByteBuffer _bb, FbsServerTick obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsServerTick __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long ServerTick { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FbsClassM.FbsServerTick> CreateFbsServerTick(FlatBufferBuilder builder,
      long serverTick = 0) {
    builder.StartTable(1);
    FbsServerTick.AddServerTick(builder, serverTick);
    return FbsServerTick.EndFbsServerTick(builder);
  }

  public static void StartFbsServerTick(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddServerTick(FlatBufferBuilder builder, long serverTick) { builder.AddLong(0, serverTick, 0); }
  public static Offset<FbsClassM.FbsServerTick> EndFbsServerTick(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsServerTick>(o);
  }
}


static public class FbsServerTickVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ServerTick*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
