// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FbsClassM
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

///////////////////////////////////////////////////////////////
public struct FbsStrArray : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FbsStrArray GetRootAsFbsStrArray(ByteBuffer _bb) { return GetRootAsFbsStrArray(_bb, new FbsStrArray()); }
  public static FbsStrArray GetRootAsFbsStrArray(ByteBuffer _bb, FbsStrArray obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FbsStrArray __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ArrStr(int j) { int o = __p.__offset(4); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int ArrStrLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FbsClassM.FbsStrArray> CreateFbsStrArray(FlatBufferBuilder builder,
      VectorOffset arrStrOffset = default(VectorOffset)) {
    builder.StartTable(1);
    FbsStrArray.AddArrStr(builder, arrStrOffset);
    return FbsStrArray.EndFbsStrArray(builder);
  }

  public static void StartFbsStrArray(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddArrStr(FlatBufferBuilder builder, VectorOffset arrStrOffset) { builder.AddOffset(0, arrStrOffset.Value, 0); }
  public static VectorOffset CreateArrStrVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateArrStrVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateArrStrVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateArrStrVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartArrStrVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FbsClassM.FbsStrArray> EndFbsStrArray(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FbsClassM.FbsStrArray>(o);
  }
}


static public class FbsStrArrayVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfStrings(tablePos, 4 /*ArrStr*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
