using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using ChServerM.SourceGen;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace ChServerM.SourceGen.Tests;

/// <summary>
/// <see cref="MessageHandlerGenerator"/> 의 드라이버 테스트 — 진단(CHSM1xxx)과 생성 코드.
/// </summary>
/// <remarks>
/// <para>
/// <b>스냅샷 규약(ROADMAP Phase 7).</b> <see cref="Snapshot_GeneratedSource_IsStable"/> 이
/// 생성 코드 전문을 고정한다. 생성 코드를 의도적으로 바꿨다면 이 테스트의 기대 문자열을
/// 함께 바꿔야 하고, 그 diff 가 리뷰에 노출된다 — PublicAPI 승인 파일과 같은 목적이다.
/// </para>
/// <para>줄바꿈은 비교 전에 LF 로 정규화한다 — 생성기는 실행 OS 의 개행을 쓴다.</para>
/// </remarks>
public sealed class MessageHandlerGeneratorTests
{
    private const string ValidSource = """
        using System.Threading.Tasks;
        using ChServerM.Dispatch;

        namespace TestApp;

        public sealed class ChatMessage { public string Text { get; set; } = ""; }
        public sealed class MoveMessage { public int X { get; set; } }

        [MessageHandler(200)]
        public sealed class MoveHandler : IMessageHandler<MoveMessage>
        {
            public ValueTask HandleAsync(MessageContext context, MoveMessage message) => default;
        }

        [MessageHandler(100)]
        public sealed class ChatHandler : IMessageHandler<ChatMessage>
        {
            public ValueTask HandleAsync(MessageContext context, ChatMessage message) => default;
        }
        """;

    [Fact]
    public void ValidHandlers_NoDiagnostics_OutputCompiles()
    {
        (GeneratorRunResult result, Compilation output) = Run(ValidSource);

        Assert.Empty(result.Diagnostics);
        Assert.Single(result.GeneratedSources);

        // 생성 코드까지 포함한 전체 컴파일레이션이 오류 없이 컴파일돼야 한다 —
        // 생성 문자열이 문법적으로 맞다는 가장 강한 검증이다.
        Diagnostic[] errors = [.. output.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error)];
        Assert.Empty(errors);
    }

    [Fact]
    public void Snapshot_GeneratedSource_IsStable()
    {
        (GeneratorRunResult result, _) = Run(ValidSource);

        string generated = Normalize(result.GeneratedSources[0].SourceText.ToString());

        // 핸들러는 ID 오름차순(100, 200)으로 정렬된다 — 선언 순서(200, 100)가 아니다.
        const string Expected = """
            // <auto-generated/>
            // ChServerM.SourceGen 이 [MessageHandler] 선언에서 생성했다. 직접 수정하지 않는다.
            #nullable enable

            namespace ChServerM.Dispatch.Generated
            {
                /// <summary>[MessageHandler] 핸들러의 컴파일 타임 등록 맵.</summary>
                internal static class GeneratedMessageHandlerMap
                {
                    /// <summary>이 어셈블리의 모든 [MessageHandler] 핸들러를 등록한다.</summary>
                    /// <remarks>중복 ID·계약 위반은 이미 컴파일 타임에 걸러졌다(CHSM1xxx).</remarks>
                    public static global::ChServerM.Hosting.Dispatch.MessageDispatcherBuilder MapGeneratedHandlers(
                        this global::ChServerM.Hosting.Dispatch.MessageDispatcherBuilder builder,
                        global::ChServerM.Serialization.IMessageSerializerProvider serializers,
                        global::TestApp.ChatHandler handler100,
                        global::TestApp.MoveHandler handler200)
                    {
                        if (builder is null) { throw new global::System.ArgumentNullException(nameof(builder)); }
                        if (serializers is null) { throw new global::System.ArgumentNullException(nameof(serializers)); }

                        builder.Map(
                            new global::ChServerM.Identity.MessageId(100),
                            Require<global::TestApp.ChatMessage>(serializers),
                            handler100);
                        builder.Map(
                            new global::ChServerM.Identity.MessageId(200),
                            Require<global::TestApp.MoveMessage>(serializers),
                            handler200);

                        return builder;
                    }

                    private static global::ChServerM.Serialization.IMessageSerializer<TMessage> Require<TMessage>(
                        global::ChServerM.Serialization.IMessageSerializerProvider serializers)
                        => serializers.Find<TMessage>()
                           ?? throw new global::System.InvalidOperationException(
                               $"{typeof(TMessage)} 의 직렬화기가 제공자에 없다. 조립 오류다 — 제공자 등록을 확인하라.");
                }
            }
            """;

        Assert.Equal(Normalize(Expected), generated);
    }

    [Fact]
    public void DuplicateId_ReportsCHSM1001_OnBothLocations_AndGeneratesNothing()
    {
        const string Source = """
            using System.Threading.Tasks;
            using ChServerM.Dispatch;

            namespace TestApp;

            public sealed class ChatMessage { }

            [MessageHandler(100)]
            public sealed class A : IMessageHandler<ChatMessage>
            {
                public ValueTask HandleAsync(MessageContext context, ChatMessage message) => default;
            }

            [MessageHandler(100)]
            public sealed class B : IMessageHandler<ChatMessage>
            {
                public ValueTask HandleAsync(MessageContext context, ChatMessage message) => default;
            }
            """;

        (GeneratorRunResult result, _) = Run(Source);

        Assert.Equal(2, result.Diagnostics.Count(d => d.Id == "CHSM1001"));
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void NotAHandler_ReportsCHSM1002()
    {
        const string Source = """
            using ChServerM.Dispatch;

            namespace TestApp;

            [MessageHandler(100)]
            public sealed class NotAHandler
            {
            }
            """;

        (GeneratorRunResult result, _) = Run(Source);

        Assert.Contains(result.Diagnostics, d => d.Id == "CHSM1002");
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void SentinelId_ReportsCHSM1003()
    {
        const string Source = """
            using System.Threading.Tasks;
            using ChServerM.Dispatch;

            namespace TestApp;

            public sealed class ChatMessage { }

            [MessageHandler(0)]
            public sealed class ZeroHandler : IMessageHandler<ChatMessage>
            {
                public ValueTask HandleAsync(MessageContext context, ChatMessage message) => default;
            }
            """;

        (GeneratorRunResult result, _) = Run(Source);

        Assert.Contains(result.Diagnostics, d => d.Id == "CHSM1003");
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void MultipleHandlerInterfaces_ReportsCHSM1004()
    {
        const string Source = """
            using System.Threading.Tasks;
            using ChServerM.Dispatch;

            namespace TestApp;

            public sealed class ChatMessage { }
            public sealed class MoveMessage { }

            [MessageHandler(100)]
            public sealed class BothHandler : IMessageHandler<ChatMessage>, IMessageHandler<MoveMessage>
            {
                public ValueTask HandleAsync(MessageContext context, ChatMessage message) => default;
                public ValueTask HandleAsync(MessageContext context, MoveMessage message) => default;
            }
            """;

        (GeneratorRunResult result, _) = Run(Source);

        Assert.Contains(result.Diagnostics, d => d.Id == "CHSM1004");
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void FrameworkReservedId_WarnsCHSM1005_ButStillGenerates()
    {
        const string Source = """
            using System.Threading.Tasks;
            using ChServerM.Dispatch;

            namespace TestApp;

            public sealed class ChatMessage { }

            [MessageHandler(40001)]
            public sealed class ReservedHandler : IMessageHandler<ChatMessage>
            {
                public ValueTask HandleAsync(MessageContext context, ChatMessage message) => default;
            }
            """;

        (GeneratorRunResult result, _) = Run(Source);

        Diagnostic warning = Assert.Single(result.Diagnostics);
        Assert.Equal("CHSM1005", warning.Id);
        Assert.Equal(DiagnosticSeverity.Warning, warning.Severity);
        Assert.Single(result.GeneratedSources);
    }

    [Fact]
    public void AbstractHandler_ReportsCHSM1006()
    {
        const string Source = """
            using System.Threading.Tasks;
            using ChServerM.Dispatch;

            namespace TestApp;

            public sealed class ChatMessage { }

            [MessageHandler(100)]
            public abstract class AbstractHandler : IMessageHandler<ChatMessage>
            {
                public ValueTask HandleAsync(MessageContext context, ChatMessage message) => default;
            }
            """;

        (GeneratorRunResult result, _) = Run(Source);

        Assert.Contains(result.Diagnostics, d => d.Id == "CHSM1006");
        Assert.Empty(result.GeneratedSources);
    }

    [Fact]
    public void WithoutHostingReference_WarnsCHSM1007_ValidationStillRuns()
    {
        const string Source = """
            using System.Threading.Tasks;
            using ChServerM.Dispatch;

            namespace TestApp;

            public sealed class ChatMessage { }

            [MessageHandler(0)]
            public sealed class ZeroHandler : IMessageHandler<ChatMessage>
            {
                public ValueTask HandleAsync(MessageContext context, ChatMessage message) => default;
            }

            [MessageHandler(100)]
            public sealed class OkHandler : IMessageHandler<ChatMessage>
            {
                public ValueTask HandleAsync(MessageContext context, ChatMessage message) => default;
            }
            """;

        (GeneratorRunResult result, _) = Run(Source, referenceHosting: false);

        // 검증(센티넬 ID)은 Hosting 없이도 돌고, 생성만 건너뛴다.
        Assert.Contains(result.Diagnostics, d => d.Id == "CHSM1003");
        Assert.Contains(result.Diagnostics, d => d.Id == "CHSM1007");
        Assert.Empty(result.GeneratedSources);
    }

    // ── 드라이버 도우미 ──────────────────────────────────────────────

    private static (GeneratorRunResult Result, Compilation Output) Run(string source, bool referenceHosting = true)
    {
        List<MetadataReference> references = [];

        // 테스트 러너 런타임의 참조 어셈블리 — BCL 해석용 표준 트릭.
        // ⚠ TPA 에는 러너가 로드한 ChServerM.* dll 도 들어 있다. 걸러내지 않으면
        // "Hosting 미참조" 시나리오가 성립하지 않는다(실제로 그렇게 한 번 깨졌다).
        string platformAssemblies = (string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!;
        foreach (string path in platformAssemblies.Split(Path.PathSeparator))
        {
            if (path.Length > 0
                && !Path.GetFileName(path).StartsWith("ChServerM.", StringComparison.Ordinal))
            {
                references.Add(MetadataReference.CreateFromFile(path));
            }
        }

        references.Add(MetadataReference.CreateFromFile(typeof(ChServerM.Identity.MessageId).Assembly.Location));

        if (referenceHosting)
        {
            references.Add(MetadataReference.CreateFromFile(
                typeof(ChServerM.Hosting.Dispatch.MessageDispatcherBuilder).Assembly.Location));
        }

        CSharpCompilation compilation = CSharpCompilation.Create(
            "GeneratorTestAssembly",
            [CSharpSyntaxTree.ParseText(source)],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        GeneratorDriver driver = CSharpGeneratorDriver
            .Create(new MessageHandlerGenerator())
            .RunGeneratorsAndUpdateCompilation(compilation, out Compilation output, out _);

        return (driver.GetRunResult().Results[0], output);
    }

    private static string Normalize(string text) =>
        text.Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd('\n');
}
